function [fitresult, gof] = PolynomialFit(x, y, degree)
%
%  Create a polynomial fit.
%
%
%      X Input : criterion_vect
%      Y Output: y - metaocognition measure
%       For mratio and meta-d', degree =1
%       For type-2 AUC and phi, degree =2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%

%  Auto-generated by MATLAB on 16-Oct-2018 15:25:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
if degree == 1
    ft = fittype('poly1');
else
    ft = fittype( 'poly2' );
end

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
%figure;
% h = plot( fitresult, xData, yData);
% legend( h, 'Data', 'Fitted curve', 'Location', 'NorthEast' );
% set(h,'linewidth',2)


